Add org.opensuse.RebootMgr.service for DBus activation
By using dbus activation, rebootmgrd is started on demand instead of causing

Error: The name org.opensuse.RebootMgr was not provided by any .service files